install.packages("e1071")
library(e1071)
install.packages("mlbench")
library(mlbench)
data("PimaIndiansDiabetes")
View(PimaIndiansDiabetes)
head(PimaIndiansDiabetes)
set.seed(123)
index=sample(1:nrow(PimaIndiansDiabetes),0.7*nrow(PimaIndiansDiabetes))
train=PimaIndiansDiabetes[index,]
test=PimaIndiansDiabetes[-index,]
trainl=PimaIndiansDiabetes[index,5]
testl=PimaIndiansDiabetes[-index,5]
svm_mod=svm(diabetes~mass+pressure+insulin,data=train,kernel="linear")
pre=predict(svm_mod,test)
cf=table(pre,test$diabetes)
cf
accuracy=sum(diag(cf))/sum(cf)
accuracy
